[project]
name = "nlp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "huggingface-hub[cli]>=0.34.3",
    "onnxruntime>=1.22.1",
    "tokenizers>=0.21.4",
]

[dependency-groups]
dev = []
