[project]
name = "nlp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "onnx>=1.18.0",
    "onnxruntime>=1.22.1",
    "optimum>=1.27.0",
    "transformers>=4.54.1",
]

[dependency-groups]
dev = []
