services:
  app:
    build:
      context: ./app
    container_name: app_dev
    env_file: ./app/.env
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    depends_on:
      - db

  nlp:
    build:
      context: ./nlp
    container_name: nlp_dev
    env_file: ./nlp/.env
    volumes:
      - ./nlp:/nlp
    depends_on:
      - db

  db:
    build:
      context: ./db
    container_name: db_dev
    env_file: ./db/.env
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
      - ./db/data:/var/lib/postgresql/data
      - ./db/backup:/backup
