services:
  app_prod:
    build:
      context: ./app
      dockerfile: ./Dockerfile.prod
    container_name: app_prod
    env_file: ./app/.prod.env
    volumes:
      - ./app/cache:/app/cache
    ports:
      - "80:8080"
    depends_on:
      - db_prod
      - nlp_prod
    restart: always

  nlp_prod:
    build:
      context: ./nlp
      dockerfile: ./Dockerfile.prod
    container_name: nlp_prod
    env_file: ./nlp/.prod.env
    stop_grace_period: 2s

  db_prod:
    build:
      context: ./db
      dockerfile: ./Dockerfile.prod
    container_name: db_prod
    env_file: ./db/.prod.env
    ports:
      - "5432:5432"
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
      - ./db/data:/var/lib/postgresql/data
      - ./db/backup:/backup
