services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: go_app
    volumes:
      - ./app/log:/root/log
      - ./app/cache:/root/cache
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
    env_file: .prod.env

  db:
    image: postgres:17-alpine
    container_name: postgres_db
    environment:
      TZ: 'Asia/Tokyo'
    env_file: .prod.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
