services:
  app:
    build:
      context: .
    container_name: go_app_dev
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
    env_file: .env

  db:
    image: postgres:17-alpine
    container_name: postgres_db_dev
    environment:
      TZ: 'Asia/Tokyo'
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev:
