services:
  app:
    build:
      context: ./app
    container_name: app_dev
    env_file: ./app/.env
    volumes:
      - ./app:/app
    depends_on:
      - db

  # nlp:
  #   build:
  #     context: ./nlp
  #   container_name: nlp_dev
  #   env_file: ./nlp/.env
  #   volumes:
  #     - ./nlp:/nlp
  #   depends_on:
  #     - db

  db:
    image: postgres:17-alpine
    container_name: db_dev
    env_file: ./db/.env
    ports:
      - "5432:5432"
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
      - ./db/data:/var/lib/postgresql/data
      - ./db/backup:/backup
