version: '3.8'

services:
  app:
    build: .
    container_name: go_app
    volumes:
      - ./log:/root/log
      - ./cache:/root/cache
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db

  db:
    image: postgres:17-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: 'Asia/Tokyo'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
